### ISSUE TITLE
Error adding entities for domain humidifier with platform frigidaire

### ISSUE THREAD

**Issue by mefbgil** [bm1549/home-assistant-frigidaire#20]
Logger: homeassistant.components.humidifier
Source: custom_components/frigidaire/humidifier.py:194
Integration: Humidifier (documentation, issues)
First occurred: 1:59:41 PM (2 occurrences)
Last logged: 1:59:41 PM

Error adding entities for domain humidifier with platform frigidaire
Error while setting up frigidaire platform for humidifier
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 673, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 777, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 574, in _async_write_ha_state
    attr.update(self.extra_state_attributes or {})
  File "/config/custom_components/frigidaire/humidifier.py", line 194, in extra_state_attributes
    ).number_value
AttributeError: 'NoneType' object has no attribute 'number_value'

**Comment by mefbgil** [comment]
Model Number FGAC7044U10 worked on commit #18 but breaks with #19 .  Reverted to #18  and it works fine.

**Comment by thejevans** [comment]
There are two fixes for this. Either update humidifier.py to check for `None` when attempting to get a `number_value` from `_details`, or modify the frigidaire library to return an "empty" object instead on `None` when attempting to access a non-existent attribute so that the `number_value` call never fails. I'll let @bm1549 decide which direction to go. I'd be happy to implement the fix, though.

**Comment by bm1549** [comment]
Hey @thejevans , thanks for jumping on this and I appreciate your contribution!

My take would be to go with option 1 and update `humidifer.py` (and similarly `climate.py`) to account for the case where `_details` is `None`. The [for_code](https://github.com/bm1549/frigidaire/blob/main/frigidaire/__init__.py#L119) returns an `Optional[ApplianceDetail]` so it is the calling function's responsibility to handle this case properly
